project:
  type: website

website:
  title: "hwan-ung.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: lux
    css: styles.css
    toc: true



